// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAP0jaf1u3xs1LsH6DBXdGcX4r6YXRkPV4',
    appId: '1:992155225190:web:ff25a2afec3af7f1bef1a7',
    messagingSenderId: '992155225190',
    projectId: 'bloc-firebase-study',
    authDomain: 'bloc-firebase-study.firebaseapp.com',
    storageBucket: 'bloc-firebase-study.appspot.com',
    measurementId: 'G-PR061NY8YT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1X6_Yyz2m_W03dtCLAM-15T1tUcUlyFQ',
    appId: '1:992155225190:android:d86339ce34384699bef1a7',
    messagingSenderId: '992155225190',
    projectId: 'bloc-firebase-study',
    storageBucket: 'bloc-firebase-study.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKo2AY_m41xRFI_a9pA5PEKDYR_YOsOHg',
    appId: '1:992155225190:ios:1539b247c22bc484bef1a7',
    messagingSenderId: '992155225190',
    projectId: 'bloc-firebase-study',
    storageBucket: 'bloc-firebase-study.appspot.com',
    iosBundleId: 'com.example.blocLoginAddProduct',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKo2AY_m41xRFI_a9pA5PEKDYR_YOsOHg',
    appId: '1:992155225190:ios:1539b247c22bc484bef1a7',
    messagingSenderId: '992155225190',
    projectId: 'bloc-firebase-study',
    storageBucket: 'bloc-firebase-study.appspot.com',
    iosBundleId: 'com.example.blocLoginAddProduct',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAP0jaf1u3xs1LsH6DBXdGcX4r6YXRkPV4',
    appId: '1:992155225190:web:956ce69a011c2127bef1a7',
    messagingSenderId: '992155225190',
    projectId: 'bloc-firebase-study',
    authDomain: 'bloc-firebase-study.firebaseapp.com',
    storageBucket: 'bloc-firebase-study.appspot.com',
    measurementId: 'G-2D5KEDCJFN',
  );
}
